### ISSUE TITLE
project is not go-getable

### ISSUE THREAD

**Issue by pavel-kolesnikov** [snirlugassy/lightdb#11]
Hi, it would be helpful to have some installation instructions. Currently the project does not allow usual `go-get`-able pattern:

```
go get github.com/snirlugassy/lightdb
go get: github.com/snirlugassy/lightdb@v0.0.0-20220321153159-a1bcb62c5e27: parsing go.mod:
        module declares its path as: lightdb
                but was required as: github.com/snirlugassy/lightdb
```

**Comment by snirlugassy** [comment]
Hi Pavel,
Thank you for the feedback, I am working now on a fix.
The installation will be `go get github.com/snirlugassy/lightdb`.

**Comment by snirlugassy** [comment]
I've tested the installation on VM and it worked for me.
Please try now and let me now if this is resolved

**Comment by pavel-kolesnikov** [comment]
Seems fixed! Thanks!
